-- Generated Seed Data from ML Datasets
START TRANSACTION;
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (101, 'HN0101', '123456', 'DM Patient 101', 'ชาย', 64, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (101, 'HN0101', 0, 17.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (102, 'HN0102', '123456', 'DM Patient 102', 'หญิง', 61, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (102, 'HN0102', 0, 7.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (103, 'HN0103', '123456', 'DM Patient 103', 'หญิง', 66, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (103, 'HN0103', 0, 9.1, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (104, 'HN0104', '123456', 'DM Patient 104', 'หญิง', 80, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (104, 'HN0104', 0, 5.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (105, 'HN0105', '123456', 'DM Patient 105', 'หญิง', 64, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (105, 'HN0105', 0, 6.7, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (106, 'HN0106', '123456', 'DM Patient 106', 'หญิง', 58, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (106, 'HN0106', 0, 6.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (107, 'HN0107', '123456', 'DM Patient 107', 'ชาย', 56, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (107, 'HN0107', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (108, 'HN0108', '123456', 'DM Patient 108', 'หญิง', 62, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (108, 'HN0108', 0, 6.1, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (109, 'HN0109', '123456', 'DM Patient 109', 'ชาย', 57, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (109, 'HN0109', 0, 7.9, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (110, 'HN0110', '123456', 'DM Patient 110', 'หญิง', 71, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (110, 'HN0110', 0, 8.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (111, 'HN0111', '123456', 'DM Patient 111', 'หญิง', 54, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (111, 'HN0111', 0, 7.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (112, 'HN0112', '123456', 'DM Patient 112', 'หญิง', 61, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (112, 'HN0112', 0, 5.9, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (113, 'HN0113', '123456', 'DM Patient 113', 'หญิง', 59, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (113, 'HN0113', 0, 6.7, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (114, 'HN0114', '123456', 'DM Patient 114', 'หญิง', 61, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (114, 'HN0114', 0, 6.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (115, 'HN0115', '123456', 'DM Patient 115', 'หญิง', 58, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (115, 'HN0115', 0, 7.2, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (116, 'HN0116', '123456', 'DM Patient 116', 'หญิง', 65, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (116, 'HN0116', 0, 12.2, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (117, 'HN0117', '123456', 'DM Patient 117', 'หญิง', 68, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (117, 'HN0117', 0, 5.9, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (118, 'HN0118', '123456', 'DM Patient 118', 'หญิง', 56, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (118, 'HN0118', 0, 9.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (119, 'HN0119', '123456', 'DM Patient 119', 'หญิง', 73, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (119, 'HN0119', 0, 7.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (120, 'HN0120', '123456', 'DM Patient 120', 'ชาย', 62, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (120, 'HN0120', 0, 6.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (121, 'HN0121', '123456', 'DM Patient 121', 'ชาย', 67, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (121, 'HN0121', 0, 6.3, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (122, 'HN0122', '123456', 'DM Patient 122', 'หญิง', 76, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (122, 'HN0122', 0, 7.3, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (123, 'HN0123', '123456', 'DM Patient 123', 'ชาย', 81, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (123, 'HN0123', 0, 7.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (124, 'HN0124', '123456', 'DM Patient 124', 'หญิง', 70, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (124, 'HN0124', 0, 8.7, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (125, 'HN0125', '123456', 'DM Patient 125', 'หญิง', 63, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (125, 'HN0125', 0, 6.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (126, 'HN0126', '123456', 'DM Patient 126', 'ชาย', 63, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (126, 'HN0126', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (127, 'HN0127', '123456', 'DM Patient 127', 'หญิง', 57, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (127, 'HN0127', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (128, 'HN0128', '123456', 'DM Patient 128', 'ชาย', 61, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (128, 'HN0128', 0, 7.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (129, 'HN0129', '123456', 'DM Patient 129', 'ชาย', 81, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (129, 'HN0129', 0, 6.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (130, 'HN0130', '123456', 'DM Patient 130', 'ชาย', 69, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (130, 'HN0130', 0, 9.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (131, 'HN0131', '123456', 'DM Patient 131', 'ชาย', 70, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (131, 'HN0131', 0, 6.2, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (132, 'HN0132', '123456', 'DM Patient 132', 'หญิง', 65, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (132, 'HN0132', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (133, 'HN0133', '123456', 'DM Patient 133', 'หญิง', 71, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (133, 'HN0133', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (134, 'HN0134', '123456', 'DM Patient 134', 'ชาย', 68, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (134, 'HN0134', 0, 6.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (135, 'HN0135', '123456', 'DM Patient 135', 'หญิง', 67, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (135, 'HN0135', 0, 7.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (136, 'HN0136', '123456', 'DM Patient 136', 'ชาย', 79, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (136, 'HN0136', 0, 5.3, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (137, 'HN0137', '123456', 'DM Patient 137', 'หญิง', 50, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (137, 'HN0137', 0, 6.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (138, 'HN0138', '123456', 'DM Patient 138', 'ชาย', 81, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (138, 'HN0138', 0, 6.2, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (139, 'HN0139', '123456', 'DM Patient 139', 'ชาย', 59, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (139, 'HN0139', 0, 6.7, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (140, 'HN0140', '123456', 'DM Patient 140', 'ชาย', 62, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (140, 'HN0140', 0, 7.7, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (141, 'HN0141', '123456', 'DM Patient 141', 'หญิง', 62, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (141, 'HN0141', 0, 5.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (142, 'HN0142', '123456', 'DM Patient 142', 'ชาย', 65, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (142, 'HN0142', 0, 8.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (143, 'HN0143', '123456', 'DM Patient 143', 'หญิง', 56, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (143, 'HN0143', 0, 6.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (144, 'HN0144', '123456', 'DM Patient 144', 'หญิง', 59, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (144, 'HN0144', 0, 7.2, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (145, 'HN0145', '123456', 'DM Patient 145', 'หญิง', 58, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (145, 'HN0145', 0, 7.1, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (146, 'HN0146', '123456', 'DM Patient 146', 'หญิง', 66, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (146, 'HN0146', 0, 6.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (147, 'HN0147', '123456', 'DM Patient 147', 'หญิง', 69, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (147, 'HN0147', 0, 17.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (148, 'HN0148', '123456', 'DM Patient 148', 'หญิง', 78, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (148, 'HN0148', 0, 6.9, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (149, 'HN0149', '123456', 'DM Patient 149', 'ชาย', 64, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (149, 'HN0149', 0, 7.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (150, 'HN0150', '123456', 'DM Patient 150', 'ชาย', 58, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (150, 'HN0150', 0, 6.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (151, 'HN0151', '123456', 'DM Patient 151', 'ชาย', 75, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (151, 'HN0151', 0, 8.3, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (152, 'HN0152', '123456', 'DM Patient 152', 'ชาย', 41, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (152, 'HN0152', 0, 6.9, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (153, 'HN0153', '123456', 'DM Patient 153', 'ชาย', 69, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (153, 'HN0153', 0, 6.1, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (154, 'HN0154', '123456', 'DM Patient 154', 'ชาย', 56, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (154, 'HN0154', 0, 8.6, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (155, 'HN0155', '123456', 'DM Patient 155', 'ชาย', 72, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (155, 'HN0155', 0, 5.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (156, 'HN0156', '123456', 'DM Patient 156', 'หญิง', 81, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (156, 'HN0156', 0, 12.8, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (157, 'HN0157', '123456', 'DM Patient 157', 'หญิง', 70, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (157, 'HN0157', 0, 6.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (158, 'HN0158', '123456', 'DM Patient 158', 'หญิง', 66, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (158, 'HN0158', 0, 5.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (159, 'HN0159', '123456', 'DM Patient 159', 'หญิง', 67, 'Type 2 Diabetes Mellitus', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, hba1c, med_metformin) VALUES (159, 'HN0159', 0, 6.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (160, 'HN0160', '123456', 'HT Patient 160', 'หญิง', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (160, 'HN0160', 0, 142.0, 83.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (161, 'HN0161', '123456', 'HT Patient 161', 'หญิง', 63, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (161, 'HN0161', 0, 149.67, 80.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (162, 'HN0162', '123456', 'HT Patient 162', 'หญิง', 71, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (162, 'HN0162', 0, 131.0, 65.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (163, 'HN0163', '123456', 'HT Patient 163', 'หญิง', 59, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (163, 'HN0163', 0, 142.0, 77.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (164, 'HN0164', '123456', 'HT Patient 164', 'หญิง', 54, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (164, 'HN0164', 0, 144.5, 92.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (165, 'HN0165', '123456', 'HT Patient 165', 'หญิง', 65, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (165, 'HN0165', 0, 127.0, 64.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (166, 'HN0166', '123456', 'HT Patient 166', 'หญิง', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (166, 'HN0166', 0, 156.0, 92.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (167, 'HN0167', '123456', 'HT Patient 167', 'ชาย', 67, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (167, 'HN0167', 0, 131.0, 86.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (168, 'HN0168', '123456', 'HT Patient 168', 'ชาย', 72, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (168, 'HN0168', 0, 162.0, 90.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (169, 'HN0169', '123456', 'HT Patient 169', 'ชาย', 56, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (169, 'HN0169', 0, 174.0, 85.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (170, 'HN0170', '123456', 'HT Patient 170', 'หญิง', 54, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (170, 'HN0170', 0, 148.86, 92.14, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (171, 'HN0171', '123456', 'HT Patient 171', 'หญิง', 53, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (171, 'HN0171', 0, 176.17, 96.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (172, 'HN0172', '123456', 'HT Patient 172', 'หญิง', 65, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (172, 'HN0172', 0, 146.33, 78.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (173, 'HN0173', '123456', 'HT Patient 173', 'หญิง', 60, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (173, 'HN0173', 0, 130.33, 71.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (174, 'HN0174', '123456', 'HT Patient 174', 'หญิง', 53, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (174, 'HN0174', 0, 139.25, 86.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (175, 'HN0175', '123456', 'HT Patient 175', 'หญิง', 63, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (175, 'HN0175', 0, 169.0, 93.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (176, 'HN0176', '123456', 'HT Patient 176', 'หญิง', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (176, 'HN0176', 0, 147.75, 93.25, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (177, 'HN0177', '123456', 'HT Patient 177', 'หญิง', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (177, 'HN0177', 0, 132.67, 78.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (178, 'HN0178', '123456', 'HT Patient 178', 'หญิง', 76, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (178, 'HN0178', 0, 144.5, 66.25, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (179, 'HN0179', '123456', 'HT Patient 179', 'ชาย', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (179, 'HN0179', 0, 174.0, 73.33, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (180, 'HN0180', '123456', 'HT Patient 180', 'หญิง', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (180, 'HN0180', 0, 132.0, 85.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (181, 'HN0181', '123456', 'HT Patient 181', 'หญิง', 79, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (181, 'HN0181', 0, 154.0, 76.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (182, 'HN0182', '123456', 'HT Patient 182', 'หญิง', 62, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (182, 'HN0182', 0, 125.0, 72.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (183, 'HN0183', '123456', 'HT Patient 183', 'หญิง', 53, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (183, 'HN0183', 0, 155.8, 88.4, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (184, 'HN0184', '123456', 'HT Patient 184', 'หญิง', 67, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (184, 'HN0184', 0, 158.0, 59.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (185, 'HN0185', '123456', 'HT Patient 185', 'ชาย', 57, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (185, 'HN0185', 0, 133.0, 73.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (186, 'HN0186', '123456', 'HT Patient 186', 'หญิง', 56, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (186, 'HN0186', 0, 141.5, 82.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (187, 'HN0187', '123456', 'HT Patient 187', 'หญิง', 67, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (187, 'HN0187', 0, 136.5, 58.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (188, 'HN0188', '123456', 'HT Patient 188', 'หญิง', 71, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (188, 'HN0188', 0, 135.33, 64.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (189, 'HN0189', '123456', 'HT Patient 189', 'หญิง', 68, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (189, 'HN0189', 0, 163.0, 74.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (190, 'HN0190', '123456', 'HT Patient 190', 'หญิง', 70, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (190, 'HN0190', 0, 118.0, 53.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (191, 'HN0191', '123456', 'HT Patient 191', 'หญิง', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (191, 'HN0191', 0, 113.0, 66.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (192, 'HN0192', '123456', 'HT Patient 192', 'หญิง', 79, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (192, 'HN0192', 0, 143.0, 77.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (193, 'HN0193', '123456', 'HT Patient 193', 'หญิง', 72, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (193, 'HN0193', 0, 137.0, 71.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (194, 'HN0194', '123456', 'HT Patient 194', 'หญิง', 43, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (194, 'HN0194', 0, 127.0, 88.25, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (195, 'HN0195', '123456', 'HT Patient 195', 'หญิง', 57, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (195, 'HN0195', 0, 143.0, 91.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (196, 'HN0196', '123456', 'HT Patient 196', 'หญิง', 70, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (196, 'HN0196', 0, 153.0, 72.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (197, 'HN0197', '123456', 'HT Patient 197', 'หญิง', 66, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (197, 'HN0197', 0, 121.5, 82.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (198, 'HN0198', '123456', 'HT Patient 198', 'หญิง', 72, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (198, 'HN0198', 0, 135.5, 62.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (199, 'HN0199', '123456', 'HT Patient 199', 'หญิง', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (199, 'HN0199', 0, 143.0, 84.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (200, 'HN0200', '123456', 'HT Patient 200', 'หญิง', 65, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (200, 'HN0200', 0, 149.0, 85.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (201, 'HN0201', '123456', 'HT Patient 201', 'หญิง', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (201, 'HN0201', 0, 107.83, 75.17, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (202, 'HN0202', '123456', 'HT Patient 202', 'หญิง', 66, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (202, 'HN0202', 0, 140.0, 73.75, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (203, 'HN0203', '123456', 'HT Patient 203', 'หญิง', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (203, 'HN0203', 0, 154.67, 86.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (204, 'HN0204', '123456', 'HT Patient 204', 'หญิง', 68, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (204, 'HN0204', 0, 130.0, 80.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (205, 'HN0205', '123456', 'HT Patient 205', 'หญิง', 65, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (205, 'HN0205', 0, 161.0, 78.67, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (206, 'HN0206', '123456', 'HT Patient 206', 'หญิง', 42, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (206, 'HN0206', 0, 125.33, 82.33, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (207, 'HN0207', '123456', 'HT Patient 207', 'หญิง', 60, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (207, 'HN0207', 0, 114.0, 57.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (208, 'HN0208', '123456', 'HT Patient 208', 'หญิง', 76, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (208, 'HN0208', 0, 155.0, 71.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (209, 'HN0209', '123456', 'HT Patient 209', 'หญิง', 70, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (209, 'HN0209', 0, 94.5, 59.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (210, 'HN0210', '123456', 'HT Patient 210', 'หญิง', 61, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (210, 'HN0210', 0, 152.0, 90.75, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (211, 'HN0211', '123456', 'HT Patient 211', 'หญิง', 64, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (211, 'HN0211', 0, 153.0, 81.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (212, 'HN0212', '123456', 'HT Patient 212', 'หญิง', 52, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (212, 'HN0212', 0, 140.0, 87.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (213, 'HN0213', '123456', 'HT Patient 213', 'หญิง', 56, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (213, 'HN0213', 0, 128.0, 84.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (214, 'HN0214', '123456', 'HT Patient 214', 'หญิง', 68, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (214, 'HN0214', 0, 140.0, 69.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (215, 'HN0215', '123456', 'HT Patient 215', 'หญิง', 83, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (215, 'HN0215', 0, 222.0, 97.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (216, 'HN0216', '123456', 'HT Patient 216', 'หญิง', 73, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (216, 'HN0216', 0, 166.0, 83.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (217, 'HN0217', '123456', 'HT Patient 217', 'หญิง', 59, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (217, 'HN0217', 0, 126.0, 70.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (218, 'HN0218', '123456', 'HT Patient 218', 'หญิง', 74, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (218, 'HN0218', 0, 168.0, 65.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (219, 'HN0219', '123456', 'HT Patient 219', 'หญิง', 51, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (219, 'HN0219', 0, 177.33, 92.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (220, 'HN0220', '123456', 'HT Patient 220', 'ชาย', 65, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (220, 'HN0220', 0, 121.0, 66.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (221, 'HN0221', '123456', 'HT Patient 221', 'ชาย', 66, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (221, 'HN0221', 0, 130.0, 78.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (222, 'HN0222', '123456', 'HT Patient 222', 'ชาย', 44, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (222, 'HN0222', 0, 144.0, 82.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (223, 'HN0223', '123456', 'HT Patient 223', 'ชาย', 58, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (223, 'HN0223', 0, 149.5, 108.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (224, 'HN0224', '123456', 'HT Patient 224', 'หญิง', 76, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (224, 'HN0224', 0, 135.0, 65.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (225, 'HN0225', '123456', 'HT Patient 225', 'ชาย', 64, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (225, 'HN0225', 0, 154.5, 86.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (226, 'HN0226', '123456', 'HT Patient 226', 'หญิง', 63, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (226, 'HN0226', 0, 147.5, 92.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (227, 'HN0227', '123456', 'HT Patient 227', 'ชาย', 81, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (227, 'HN0227', 0, 187.0, 86.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (228, 'HN0228', '123456', 'HT Patient 228', 'หญิง', 63, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (228, 'HN0228', 0, 130.0, 77.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (229, 'HN0229', '123456', 'HT Patient 229', 'หญิง', 74, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (229, 'HN0229', 0, 131.67, 65.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (230, 'HN0230', '123456', 'HT Patient 230', 'หญิง', 70, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (230, 'HN0230', 0, 140.0, 82.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (231, 'HN0231', '123456', 'HT Patient 231', 'หญิง', 60, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (231, 'HN0231', 0, 144.0, 81.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (232, 'HN0232', '123456', 'HT Patient 232', 'ชาย', 55, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (232, 'HN0232', 0, 128.0, 77.0, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (233, 'HN0233', '123456', 'HT Patient 233', 'หญิง', 64, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (233, 'HN0233', 0, 154.0, 77.33, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (234, 'HN0234', '123456', 'HT Patient 234', 'หญิง', 75, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (234, 'HN0234', 0, 184.5, 91.5, 1);
INSERT INTO patients (id, hn, password, full_name, gender, age, disease, care_area) VALUES (235, 'HN0235', '123456', 'HT Patient 235', 'หญิง', 75, 'Hypertension', 'OPD') ON CONFLICT (id) DO NOTHING;
INSERT INTO patient_longitudinal_records (patient_id, hn, period_offset, systolic, diastolic, med_ccb) VALUES (235, 'HN0235', 0, 169.75, 81.75, 1);
COMMIT;